name: app_objetos_perdidos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  uuid: ^4.5.1
  path_provider: ^2.0.11
  google_maps_flutter: ^2.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.10
  font_awesome_flutter: ^10.7.0
  google_generative_ai: ^0.4.0
  flutter_dotenv: ^5.1.0
  latlong2: ^0.9.1
  image_picker: ^1.2.0
  connectivity_plus: ^6.1.5
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - .env
